version: '3.6'

services:
  postgres:
    container_name: workshop-postgres
    image: postgres:14.6-alpine
    environment:
      POSTGRES_DB: workshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: always
    ports:
      - 5432:5432